/**
 * Hand-maintained catalog of every Next.js Route Handler under `app/api/**`,
 * powering the interactive tester at `/api-docs`. Keep in sync with the route
 * files and `packages/shared/src/types/entities.ts`'s *CreateInput/*UpdateInput
 * schemas when either changes — there's no runtime introspection here, this is
 * the source of truth for the docs page.
 */

export type AuthLevel = "public" | "user" | "admin" | "internal";

export interface ApiParam {
  name: string;
  example?: string;
  description?: string;
  required?: boolean;
}

export interface ApiEndpoint {
  id: string;
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string; // template with :param placeholders
  category: string;
  auth: AuthLevel;
  summary: string;
  description?: string;
  pathParams?: ApiParam[];
  queryParams?: ApiParam[];
  requestBodyExample?: unknown;
  responseExample?: unknown;
  notes?: string;
}

const EX_UUID = "00000000-0000-0000-0000-000000000000";
const EX_LISTING_ID = "11111111-1111-1111-1111-111111111111";
const EX_ORDER_ID = "22222222-2222-2222-2222-222222222222";
const EX_USER_ID = "33333333-3333-3333-3333-333333333333";

export const API_CATALOG: ApiEndpoint[] = [
  // ============================================================== Profile
  {
    id: "get-profile",
    method: "GET",
    path: "/api/profile",
    category: "Profile",
    auth: "user",
    summary: "Get your own profile",
    responseExample: { profile: { id: EX_UUID, email: "you@example.com", role: "user", display_name: "Reef Fan", language: "en", country: "US", seller_agreed: false, eula_accepted: false } },
  },
  {
    id: "update-profile",
    method: "PATCH",
    path: "/api/profile",
    category: "Profile",
    auth: "user",
    summary: "Update your own profile",
    requestBodyExample: { display_name: "Reef Fan", bio: "Saltwater hobbyist since 2019", location: "San Diego, CA", language: "en", country: "US" },
    responseExample: { profile: { id: EX_UUID, display_name: "Reef Fan" } },
  },
  {
    id: "delete-profile",
    method: "DELETE",
    path: "/api/profile",
    category: "Profile",
    auth: "user",
    summary: "Delete your account",
    description: "Hard-deletes if you have no order history, otherwise anonymizes + bans (orders.buyer_id/seller_id are ON DELETE RESTRICT).",
    responseExample: { anonymized: false },
  },
  {
    id: "get-public-profile",
    method: "GET",
    path: "/api/profiles/:id",
    category: "Profile",
    auth: "public",
    summary: "Get a public seller profile",
    pathParams: [{ name: "id", example: EX_USER_ID }],
    responseExample: { profile: { id: EX_USER_ID, display_name: "Reef Fan", verified_seller: false, completed_sales_count: 3 } },
  },
  {
    id: "agree-seller-terms",
    method: "POST",
    path: "/api/profile/seller-agreement",
    category: "Profile",
    auth: "user",
    summary: "Accept the Seller Agreement",
    description: "One-way flip of profiles.seller_agreed to true. No request body.",
    responseExample: { profile: { seller_agreed: true } },
  },
  {
    id: "accept-eula",
    method: "POST",
    path: "/api/profile/eula",
    category: "Profile",
    auth: "user",
    summary: "Accept the EULA",
    description: "One-way flip of profiles.eula_accepted to true. No request body.",
    responseExample: { profile: { eula_accepted: true } },
  },

  // ============================================================== Listings
  {
    id: "list-listings",
    method: "GET",
    path: "/api/listings",
    category: "Listings",
    auth: "public",
    summary: "Browse/search listings",
    queryParams: [
      { name: "market", example: "saltwater", description: "saltwater | freshwater" },
      { name: "listing_type", example: "coral" },
      { name: "category", example: "LPS Corals" },
      { name: "q", example: "clownfish" },
      { name: "min_price", example: "10" },
      { name: "max_price", example: "100" },
      { name: "shipping", example: "local_pickup", description: "local_pickup | shipping" },
      { name: "featured", example: "true" },
      { name: "seller_id", example: EX_USER_ID },
      { name: "sort", example: "newest", description: "newest | price_low | price_high | featured" },
      { name: "lat", example: "32.7157", description: "Combine with lng + radius_miles for location search" },
      { name: "lng", example: "-117.1611" },
      { name: "radius_miles", example: "50" },
      { name: "limit", example: "50" },
      { name: "offset", example: "0" },
    ],
    responseExample: { listings: [{ id: EX_LISTING_ID, title: "Rainbow Acan Frag", price: 25, status: "active" }], total: 1 },
  },
  {
    id: "get-listing",
    method: "GET",
    path: "/api/listings/:id",
    category: "Listings",
    auth: "public",
    summary: "Get a single listing",
    pathParams: [{ name: "id", example: EX_LISTING_ID }],
    responseExample: { listing: { id: EX_LISTING_ID, title: "Rainbow Acan Frag", price: 25 } },
  },
  {
    id: "create-listing",
    method: "POST",
    path: "/api/listings",
    category: "Listings",
    auth: "user",
    summary: "Create a listing",
    description: "Enforces the plan-based active-listing cap (see GET /api/listings/limit).",
    requestBodyExample: {
      title: "Rainbow Acan Frag",
      description: "Beautiful rainbow acan, 1.5in frag.",
      market: "saltwater",
      listing_type: "coral",
      category: "LPS Corals",
      price: 25,
      currency: "USD",
      quantity: 3,
      photos: ["https://example.com/photo1.jpg"],
      photo_type: "actual_photo",
      shipping_available: true,
      local_pickup: true,
      shipping_cost: 15,
      min_qty: 1,
      min_order_amount: 0,
      pickup_address: "123 Reef St, San Diego, CA",
      pickup_times: ["Sat, Sun 10:00 AM – 2:00 PM"],
      doa_policy: "full_refund",
      frag_size: "1.5 inch",
      light_requirement: "medium",
      flow_requirement: "medium",
      difficulty: "beginner",
      care_notes: "Moderate light and flow, feeds well on target feeding.",
      wysiwyg: true,
      seller_country: "US",
      ships_to_countries: [],
      featured_fee: false,
    },
    responseExample: { listing: { id: EX_LISTING_ID, status: "active" } },
  },
  {
    id: "update-listing",
    method: "PATCH",
    path: "/api/listings/:id",
    category: "Listings",
    auth: "user",
    summary: "Update a listing (owner or admin)",
    pathParams: [{ name: "id", example: EX_LISTING_ID }],
    requestBodyExample: { price: 22, quantity: 2, status: "active" },
    responseExample: { listing: { id: EX_LISTING_ID, price: 22 } },
  },
  {
    id: "delete-listing",
    method: "DELETE",
    path: "/api/listings/:id",
    category: "Listings",
    auth: "user",
    summary: "Hard-delete a listing (owner or admin)",
    pathParams: [{ name: "id", example: EX_LISTING_ID }],
    responseExample: { deleted: true },
  },
  {
    id: "listing-limit",
    method: "GET",
    path: "/api/listings/limit",
    category: "Listings",
    auth: "user",
    summary: "Check your active-listing cap usage",
    responseExample: { allowed: true, usage: { active: 2, max: 5 } },
  },

  // ============================================================== Services
  {
    id: "list-services",
    method: "GET",
    path: "/api/services",
    category: "Services",
    auth: "public",
    summary: "Browse services",
    queryParams: [
      { name: "market", example: "saltwater" },
      { name: "service_type", example: "tank_cleaning_sw" },
      { name: "provider_id", example: EX_USER_ID },
      { name: "status", example: "active" },
      { name: "limit", example: "50" },
      { name: "offset", example: "0" },
    ],
    responseExample: { services: [{ id: EX_UUID, title: "Weekly Tank Cleaning", service_type: "tank_cleaning_sw" }], total: 1 },
  },
  {
    id: "get-service",
    method: "GET",
    path: "/api/services/:id",
    category: "Services",
    auth: "public",
    summary: "Get a single service",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { service: { id: EX_UUID, title: "Weekly Tank Cleaning" } },
  },
  {
    id: "create-service",
    method: "POST",
    path: "/api/services",
    category: "Services",
    auth: "user",
    summary: "Create a service listing",
    requestBodyExample: {
      title: "Weekly Tank Cleaning",
      description: "Professional saltwater tank maintenance, all sizes.",
      service_type: "tank_cleaning_sw",
      market: "saltwater",
      price_range: "$50-150/visit",
      location: "San Diego, CA",
      service_area: "Within 20 miles",
      ships_nationwide: false,
      photos: [],
      contact_info: "Message me through the app",
    },
    responseExample: { service: { id: EX_UUID, status: "active" } },
  },
  {
    id: "update-service",
    method: "PATCH",
    path: "/api/services/:id",
    category: "Services",
    auth: "user",
    summary: "Update a service (owner or admin)",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { price_range: "$60-160/visit", status: "active" },
    responseExample: { service: { id: EX_UUID } },
  },
  {
    id: "delete-service",
    method: "DELETE",
    path: "/api/services/:id",
    category: "Services",
    auth: "user",
    summary: "Delete a service (owner or admin)",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },

  // ============================================================== Orders & Checkout
  {
    id: "checkout",
    method: "POST",
    path: "/api/orders/checkout",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Buy a single listing (creates order + Stripe PaymentIntent)",
    description: "Requires real Stripe keys configured server-side to actually return a usable clientSecret.",
    requestBodyExample: { listing_id: EX_LISTING_ID, quantity: 1, shipping_method: "local_pickup", pickup_time: "Sat, Sun 10:00 AM – 2:00 PM" },
    responseExample: { order: { id: EX_ORDER_ID, status: "pending" }, clientSecret: "pi_..._secret_..." },
  },
  {
    id: "cart-checkout",
    method: "POST",
    path: "/api/cart/checkout",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Checkout multiple cart items at once",
    description: "Each item becomes its own Order + PaymentIntent, with per-item failure isolation.",
    requestBodyExample: { items: [{ listing_id: EX_LISTING_ID, quantity: 1, shipping_method: "shipping" }] },
    responseExample: { results: [{ listing_id: EX_LISTING_ID, order: { id: EX_ORDER_ID }, clientSecret: "pi_..._secret_...", error: null }] },
  },
  {
    id: "list-orders",
    method: "GET",
    path: "/api/orders",
    category: "Orders & Checkout",
    auth: "user",
    summary: "List your orders",
    queryParams: [{ name: "role", example: "buyer", required: true, description: "buyer | seller" }],
    responseExample: { orders: [{ id: EX_ORDER_ID, status: "completed" }] },
  },
  {
    id: "get-order",
    method: "GET",
    path: "/api/orders/:id",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Get an order (buyer, seller, or admin)",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, status: "pending" } },
  },
  {
    id: "cancel-order",
    method: "POST",
    path: "/api/orders/:id/cancel",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Cancel an order",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, status: "cancelled" } },
  },
  {
    id: "ship-order",
    method: "POST",
    path: "/api/orders/:id/ship",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Seller adds tracking to mark an order shipped",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    requestBodyExample: { tracking_number: "1Z999AA10123456784", carrier: "UPS" },
    responseExample: { order: { id: EX_ORDER_ID, status: "shipped" } },
  },
  {
    id: "confirm-receipt",
    method: "POST",
    path: "/api/orders/:id/confirm-receipt",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Buyer confirms a shipped order arrived",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, status: "completed" } },
  },
  {
    id: "mark-picked-up",
    method: "POST",
    path: "/api/orders/:id/mark-picked-up",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Seller marks a local-pickup order as picked up",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, seller_marked_picked_up: true } },
  },
  {
    id: "confirm-pickup",
    method: "POST",
    path: "/api/orders/:id/confirm-pickup",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Buyer confirms a local pickup",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, status: "completed" } },
  },
  {
    id: "deny-pickup",
    method: "POST",
    path: "/api/orders/:id/deny-pickup",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Buyer disputes a seller's pickup-confirmed claim",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID } },
  },
  {
    id: "file-doa-claim",
    method: "POST",
    path: "/api/orders/:id/dispute",
    category: "Orders & Checkout",
    auth: "user",
    summary: "Buyer files a DOA (dead-on-arrival) claim",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    requestBodyExample: { reason: "Coral arrived bleached and unresponsive.", photos: ["https://example.com/doa1.jpg"] },
    responseExample: { order: { id: EX_ORDER_ID, doa_claim_status: "pending" } },
  },

  // ============================================================== Reviews
  {
    id: "create-review",
    method: "POST",
    path: "/api/reviews",
    category: "Reviews",
    auth: "user",
    summary: "Leave a review for a seller after a completed order",
    requestBodyExample: { listing_id: EX_LISTING_ID, rating: 5, comment: "Great coral, fast shipping!" },
    responseExample: { review: { id: EX_UUID, rating: 5 } },
  },
  {
    id: "seller-reviews",
    method: "GET",
    path: "/api/sellers/:id/reviews",
    category: "Reviews",
    auth: "public",
    summary: "Get a seller's reviews + average rating",
    pathParams: [{ name: "id", example: EX_USER_ID }],
    responseExample: { reviews: [{ rating: 5, comment: "Great coral!" }], averageRating: 4.8, count: 12 },
  },

  // ============================================================== Messaging
  {
    id: "list-conversations",
    method: "GET",
    path: "/api/conversations",
    category: "Messaging",
    auth: "user",
    summary: "List your conversations",
    responseExample: { conversations: [{ id: EX_UUID, last_message: { content: "Is this still available?" }, unread_count: 1 }] },
  },
  {
    id: "get-conversation-messages",
    method: "GET",
    path: "/api/conversations/:id/messages",
    category: "Messaging",
    auth: "user",
    summary: "Get a conversation's message thread",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { id: EX_UUID, messages: [{ content: "Is this still available?", sender_id: EX_USER_ID }] },
  },
  {
    id: "send-message",
    method: "POST",
    path: "/api/messages",
    category: "Messaging",
    auth: "user",
    summary: "Send a message (creates a conversation if needed)",
    requestBodyExample: { recipient_id: EX_USER_ID, listing_id: EX_LISTING_ID, content: "Is this still available?" },
    responseExample: { message: { id: EX_UUID, content: "Is this still available?" } },
  },

  // ============================================================== Watchlist & Saved Searches
  {
    id: "list-watchlist",
    method: "GET",
    path: "/api/watchlist",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "List your saved listings",
    responseExample: { listings: [{ id: EX_LISTING_ID, title: "Rainbow Acan Frag" }] },
  },
  {
    id: "add-watchlist",
    method: "POST",
    path: "/api/watchlist",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "Save a listing",
    requestBodyExample: { listing_id: EX_LISTING_ID },
    responseExample: { saved: true },
  },
  {
    id: "remove-watchlist",
    method: "DELETE",
    path: "/api/watchlist/:listingId",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "Un-save a listing",
    pathParams: [{ name: "listingId", example: EX_LISTING_ID }],
    responseExample: { saved: false },
  },
  {
    id: "list-saved-searches",
    method: "GET",
    path: "/api/saved-searches",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "List your saved searches",
    responseExample: { savedSearches: [{ id: EX_UUID, name: "Cheap LPS", is_active: true }] },
  },
  {
    id: "create-saved-search",
    method: "POST",
    path: "/api/saved-searches",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "Create a saved search",
    requestBodyExample: { name: "Cheap LPS", listing_type: "coral", category: "LPS Corals", max_price: 50, is_active: true },
    responseExample: { savedSearch: { id: EX_UUID } },
  },
  {
    id: "update-saved-search",
    method: "PATCH",
    path: "/api/saved-searches/:id",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "Update or toggle a saved search",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { is_active: false },
    responseExample: { savedSearch: { id: EX_UUID, is_active: false } },
  },
  {
    id: "delete-saved-search",
    method: "DELETE",
    path: "/api/saved-searches/:id",
    category: "Watchlist & Saved Searches",
    auth: "user",
    summary: "Delete a saved search",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },

  // ============================================================== Reports & Blocking
  {
    id: "create-report",
    method: "POST",
    path: "/api/reports",
    category: "Reports & Blocking",
    auth: "user",
    summary: "Report a listing or seller",
    requestBodyExample: { report_type: "listing", listing_id: EX_LISTING_ID, reason: "Suspected scam", details: "Price is far below market for this species." },
    responseExample: { report: { id: EX_UUID, status: "pending" } },
  },
  {
    id: "list-blocked-users",
    method: "GET",
    path: "/api/blocked-users",
    category: "Reports & Blocking",
    auth: "user",
    summary: "List users you've blocked",
    responseExample: { blockedUsers: [{ id: EX_UUID, blocked_id: EX_USER_ID }] },
  },
  {
    id: "block-user",
    method: "POST",
    path: "/api/blocked-users",
    category: "Reports & Blocking",
    auth: "user",
    summary: "Block a seller",
    requestBodyExample: { blocked_id: EX_USER_ID, reason: "Unresponsive / bad experience" },
    responseExample: { blockedUser: { id: EX_UUID } },
  },
  {
    id: "unblock-user",
    method: "DELETE",
    path: "/api/blocked-users/:id",
    category: "Reports & Blocking",
    auth: "user",
    summary: "Unblock a user",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },

  // ============================================================== Promo Codes & Subscriptions
  {
    id: "redeem-promo",
    method: "POST",
    path: "/api/promo-codes/redeem",
    category: "Promo Codes & Subscriptions",
    auth: "user",
    summary: "Redeem a promo code",
    requestBodyExample: { code: "WELCOME5" },
    responseExample: { granted: "bonus_listings" },
  },
  {
    id: "list-membership-plans",
    method: "GET",
    path: "/api/membership-plans",
    category: "Promo Codes & Subscriptions",
    auth: "public",
    summary: "List available membership plans",
    responseExample: { plans: [{ slug: "pro", name: "Pro", price_monthly: 9.99, max_active_listings: -1 }] },
  },
  {
    id: "get-own-subscription",
    method: "GET",
    path: "/api/subscriptions",
    category: "Promo Codes & Subscriptions",
    auth: "user",
    summary: "Get your current subscription + plan",
    responseExample: { subscription: null, plan: { slug: "free", max_active_listings: 5 } },
  },
  {
    id: "subscription-checkout",
    method: "POST",
    path: "/api/subscriptions/checkout",
    category: "Promo Codes & Subscriptions",
    auth: "user",
    summary: "Start a Stripe Checkout Session to upgrade plans",
    description: "Requires real Stripe keys configured server-side.",
    requestBodyExample: { plan_slug: "pro" },
    responseExample: { url: "https://checkout.stripe.com/c/pay/..." },
  },
  {
    id: "cancel-subscription",
    method: "POST",
    path: "/api/subscriptions/cancel",
    category: "Promo Codes & Subscriptions",
    auth: "user",
    summary: "Cancel your subscription (at period end)",
    responseExample: { subscription: { status: "active" } },
  },

  // ============================================================== Payouts
  {
    id: "payout-status",
    method: "GET",
    path: "/api/payouts/status",
    category: "Payouts",
    auth: "user",
    summary: "Check your Stripe Connect payout status",
    responseExample: { connected: false, payoutsEnabled: false },
  },
  {
    id: "payout-onboarding-link",
    method: "POST",
    path: "/api/payouts/onboarding-link",
    category: "Payouts",
    auth: "user",
    summary: "Get a Stripe Connect onboarding link",
    description: "Requires real Stripe keys configured server-side.",
    responseExample: { url: "https://connect.stripe.com/setup/..." },
  },

  // ============================================================== Uploads
  {
    id: "sign-upload",
    method: "POST",
    path: "/api/uploads/sign",
    category: "Uploads",
    auth: "user",
    summary: "Get a signed upload URL for a storage bucket",
    requestBodyExample: { bucket: "listing-photos", filename: "coral.jpg" },
    responseExample: { path: `${EX_USER_ID}/....jpg`, token: "...", publicUrl: "https://....supabase.co/storage/v1/object/public/listing-photos/..." },
    notes: "Allowed buckets: listing-photos, avatars, tank-photos, service-photos.",
  },

  // ============================================================== Public content
  {
    id: "get-announcement",
    method: "GET",
    path: "/api/announcements",
    category: "Content (public)",
    auth: "public",
    summary: "Get the active announcement banner, if any",
    responseExample: { announcement: null },
  },
  {
    id: "list-help-content",
    method: "GET",
    path: "/api/help-content",
    category: "Content (public)",
    auth: "public",
    summary: "List Learn-tab content",
    queryParams: [{ name: "category", example: "coral_care" }, { name: "market", example: "saltwater" }],
    responseExample: { items: [{ id: EX_UUID, title: "Reef Tank Basics", content_type: "article" }] },
  },

  // ============================================================== Admin
  {
    id: "admin-stats",
    method: "GET",
    path: "/api/admin/stats",
    category: "Admin",
    auth: "admin",
    summary: "Overview dashboard stats",
    responseExample: { listings: { total: 120, active: 100 }, users: { total: 340 }, orders: { total: 58, completed: 40, doa_claim: 1 } },
  },
  {
    id: "admin-list-users",
    method: "GET",
    path: "/api/admin/users",
    category: "Admin",
    auth: "admin",
    summary: "List/search users",
    queryParams: [{ name: "q", example: "reef" }, { name: "limit", example: "50" }, { name: "offset", example: "0" }],
    responseExample: { users: [{ id: EX_USER_ID, email: "you@example.com", role: "user" }], total: 1 },
  },
  {
    id: "admin-update-user-role",
    method: "PATCH",
    path: "/api/admin/users/:id",
    category: "Admin",
    auth: "admin",
    summary: "Change a user's role",
    pathParams: [{ name: "id", example: EX_USER_ID }],
    requestBodyExample: { role: "admin" },
    responseExample: { profile: { id: EX_USER_ID, role: "admin" } },
  },
  {
    id: "admin-list-reports",
    method: "GET",
    path: "/api/admin/reports",
    category: "Admin",
    auth: "admin",
    summary: "List reports",
    queryParams: [{ name: "status", example: "pending" }, { name: "limit", example: "50" }, { name: "offset", example: "0" }],
    responseExample: { reports: [{ id: EX_UUID, status: "pending" }], total: 1 },
  },
  {
    id: "admin-update-report",
    method: "PATCH",
    path: "/api/admin/reports/:id",
    category: "Admin",
    auth: "admin",
    summary: "Update a report's status",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { status: "resolved" },
    responseExample: { report: { id: EX_UUID, status: "resolved" } },
  },
  {
    id: "admin-refund-order",
    method: "POST",
    path: "/api/admin/orders/:id/refund",
    category: "Admin",
    auth: "admin",
    summary: "Refund or store-credit an order",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    requestBodyExample: { mode: "refund" },
    responseExample: { order: { id: EX_ORDER_ID, status: "doa_claim" } },
    notes: "mode: 'refund' | 'store_credit'. Also resolves a pending DOA claim if one exists.",
  },
  {
    id: "admin-deny-doa-claim",
    method: "POST",
    path: "/api/admin/orders/:id/deny-claim",
    category: "Admin",
    auth: "admin",
    summary: "Deny a buyer's DOA claim",
    pathParams: [{ name: "id", example: EX_ORDER_ID }],
    responseExample: { order: { id: EX_ORDER_ID, doa_claim_status: "denied" } },
  },
  {
    id: "admin-list-announcements",
    method: "GET",
    path: "/api/admin/announcements",
    category: "Admin",
    auth: "admin",
    summary: "List all announcements (CMS)",
    queryParams: [{ name: "limit", example: "50" }, { name: "offset", example: "0" }],
    responseExample: { announcements: [{ id: EX_UUID, subject: "Welcome!" }], total: 1 },
  },
  {
    id: "admin-create-announcement",
    method: "POST",
    path: "/api/admin/announcements",
    category: "Admin",
    auth: "admin",
    summary: "Create an announcement",
    requestBodyExample: { subject: "New feature!", message: "Cart checkout is now live.", is_active: true, max_views: 0, show_to_guests: true },
    responseExample: { announcement: { id: EX_UUID } },
  },
  {
    id: "admin-update-announcement",
    method: "PATCH",
    path: "/api/admin/announcements/:id",
    category: "Admin",
    auth: "admin",
    summary: "Update an announcement",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { is_active: false },
    responseExample: { announcement: { id: EX_UUID, is_active: false } },
  },
  {
    id: "admin-delete-announcement",
    method: "DELETE",
    path: "/api/admin/announcements/:id",
    category: "Admin",
    auth: "admin",
    summary: "Delete an announcement",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },
  {
    id: "admin-list-help-content",
    method: "GET",
    path: "/api/admin/help-content",
    category: "Admin",
    auth: "admin",
    summary: "List all Learn content (CMS)",
    queryParams: [{ name: "limit", example: "50" }, { name: "offset", example: "0" }],
    responseExample: { items: [{ id: EX_UUID, title: "Reef Tank Basics" }], total: 1 },
  },
  {
    id: "admin-create-help-content",
    method: "POST",
    path: "/api/admin/help-content",
    category: "Admin",
    auth: "admin",
    summary: "Create Learn content",
    requestBodyExample: { title: "Reef Tank Basics", content_type: "article", category: "beginner_setup", market: "saltwater", body: "Getting started with your first reef tank...", published: true },
    responseExample: { item: { id: EX_UUID } },
  },
  {
    id: "admin-update-help-content",
    method: "PATCH",
    path: "/api/admin/help-content/:id",
    category: "Admin",
    auth: "admin",
    summary: "Update Learn content",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { published: false },
    responseExample: { item: { id: EX_UUID, published: false } },
  },
  {
    id: "admin-delete-help-content",
    method: "DELETE",
    path: "/api/admin/help-content/:id",
    category: "Admin",
    auth: "admin",
    summary: "Delete Learn content",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },
  {
    id: "admin-list-promo-codes",
    method: "GET",
    path: "/api/admin/promo-codes",
    category: "Admin",
    auth: "admin",
    summary: "List promo codes",
    queryParams: [{ name: "limit", example: "50" }, { name: "offset", example: "0" }],
    responseExample: { promoCodes: [{ id: EX_UUID, code: "WELCOME5" }], total: 1 },
  },
  {
    id: "admin-create-promo-code",
    method: "POST",
    path: "/api/admin/promo-codes",
    category: "Admin",
    auth: "admin",
    summary: "Create a promo code",
    requestBodyExample: { code: "WELCOME5", type: "bonus_listings", bonus_listings: 5, max_uses: 100, is_active: true },
    responseExample: { promoCode: { id: EX_UUID } },
  },
  {
    id: "admin-update-promo-code",
    method: "PATCH",
    path: "/api/admin/promo-codes/:id",
    category: "Admin",
    auth: "admin",
    summary: "Update a promo code",
    pathParams: [{ name: "id", example: EX_UUID }],
    requestBodyExample: { is_active: false },
    responseExample: { promoCode: { id: EX_UUID, is_active: false } },
  },
  {
    id: "admin-delete-promo-code",
    method: "DELETE",
    path: "/api/admin/promo-codes/:id",
    category: "Admin",
    auth: "admin",
    summary: "Delete a promo code",
    pathParams: [{ name: "id", example: EX_UUID }],
    responseExample: { deleted: true },
  },

  // ============================================================== Internal (not testable here)
  {
    id: "cron-release-pickups",
    method: "POST",
    path: "/api/cron/release-pending-pickups",
    category: "Internal (not user-callable)",
    auth: "internal",
    summary: "Cron: auto-release local-pickup payments after 3 business days",
    description: "Called by a scheduled cron job with a secret, not by end users. Documented for completeness only.",
  },
  {
    id: "webhook-stripe",
    method: "POST",
    path: "/api/webhooks/stripe",
    category: "Internal (not user-callable)",
    auth: "internal",
    summary: "Stripe webhook receiver",
    description: "Verifies Stripe's signature header; only callable by Stripe itself. Documented for completeness only.",
  },
];

export const CATEGORY_ORDER = [
  "Profile",
  "Listings",
  "Services",
  "Orders & Checkout",
  "Reviews",
  "Messaging",
  "Watchlist & Saved Searches",
  "Reports & Blocking",
  "Promo Codes & Subscriptions",
  "Payouts",
  "Uploads",
  "Content (public)",
  "Admin",
  "Internal (not user-callable)",
];
